-- Continents
INSERT INTO continents (name)
VALUES ('Europe'),
       ('North America'),
       ('South America'),
       ('Africa'),
       ('Asia'),
       ('Australia');

-- Countries
INSERT INTO countries (name, continent_id)
VALUES ('France', 1),
       ('Italy', 1),
       ('United States', 2),
       ('Brazil', 3),
       ('Egypt', 4),
       ('Japan', 5),
       ('Australia', 6);

-- Countries (dodatkowe 50 krajów, pomijając istniejące)
INSERT INTO countries (name, continent_id)
         VALUES
             ('Germany', 1),
             ('United Kingdom', 1),
             ('Spain', 1),
             ('Canada', 2),
             ('Mexico', 2),
             ('Argentina', 3),
             ('Chile', 3),
             ('South Africa', 4),
             ('Nigeria', 4),
             ('Kenya', 4),
             ('China', 5),
             ('South Korea', 5),
             ('India', 5),
             ('Thailand', 5),
             ('New Zealand', 6),
             ('Fiji', 6),
             ('Indonesia', 6),
             ('Russia', 1),
             ('Sweden', 1),
             ('Netherlands', 1),
             ('Portugal', 1),
             ('Greece', 1),
             ('Switzerland', 1),
             ('Costa Rica', 3),
             ('Peru', 3),
             ('Morocco', 4),
             ('Ghana', 4),
             ('Saudi Arabia', 5),
             ('Vietnam', 5),
             ('Philippines', 5),
             ('Singapore', 5),
             ('Papua New Guinea', 6),
             ('New Caledonia', 6),
             ('Ukraine', 1),
             ('Poland', 1),
             ('Czech Republic', 1),
             ('Colombia', 3),
             ('Venezuela', 3),
             ('Tunisia', 4),
             ('Uganda', 4),
             ('Turkey', 5),
             ('Malaysia', 5),
             ('Bangladesh', 5),
             ('Sri Lanka', 5),
             ('Solomon Islands', 6),
             ('Samoa', 6);


-- Cities
INSERT INTO cities (name, country_id)
VALUES ('Paris', 1),
       ('Rome', 2),
       ('New York', 3),
       ('Rio de Janeiro', 4),
       ('Cairo', 5),
       ('Tokyo', 6),
       ('Sydney', 7);

-- Cities (dodatkowe miasta, pomijając istniejące)
INSERT INTO cities (name, country_id)
         VALUES
             ('Berlin', 9),
             ('Madrid', 8),
             ('Toronto', 9),
             ('Guadalajara', 10),
             ('Buenos Aires', 10),
             ('Santiago', 11),
             ('Johannesburg', 12),
             ('Lagos', 13),
             ('Nairobi', 14),
             ('Beijing', 15),
             ('Seoul', 16),
             ('Mumbai', 17),
             ('Bangkok', 18),
             ('Auckland', 19),
             ('Suva', 20),
             ('Bali', 21),
             ('St. Petersburg', 22),
             ('Stockholm', 23),
             ('Amsterdam', 24),
             ('Lisbon', 25),
             ('Athens', 26),
             ('Zurich', 27),
             ('San Jose', 28),
             ('Lima', 29),
             ('Rabat', 30),
             ('Accra', 31),
             ('Riyadh', 32),
             ('Hanoi', 33),
             ('Manila', 34),
             ('Singapore', 35),
             ('Port Moresby', 36),
             ('Noumea', 37),
             ('Kiev', 38),
             ('Warsaw', 39),
             ('Prague', 40),
             ('Medellin', 41),
             ('Caracas', 42),
             ('Tunis', 43),
             ('Uganda', 44),
             ('Istanbul', 45),
             ('Kuala Lumpur', 46),
             ('Dhaka', 47),
             ('Colombo', 48),
             ('Honiara', 49),
             ('Apia', 50);




-- Airports
INSERT INTO airports (IATA, name, city_id)
VALUES ('CDG', 'Paris Charles de Gaulle Airport', 1),
       ('FCO', 'Rome Fiumicino Airport', 2),
       ('JFK', 'John F. Kennedy International Airport', 3),
       ('GIG', 'Rio de Janeiro Galeão International Airport', 4),
       ('CAI', 'Cairo Airport', 5),
       ('HND', 'Tokyo Haneda Airport', 6),
       ('SYD', 'Sydney Kingsford Smith Airport', 7);

-- Airports (lotniska odpowiadające miastom)
INSERT INTO airports (IATA, name, city_id)
VALUES
    ('TXL', 'Berlin Tegel Airport', (SELECT id FROM cities WHERE name = 'Berlin')),
    ('MAD', 'Adolfo Suárez Madrid–Barajas Airport', (SELECT id FROM cities WHERE name = 'Madrid')),
    ('YYZ', 'Toronto Pearson International Airport', (SELECT id FROM cities WHERE name = 'Toronto')),
    ('GDL', 'Don Miguel Hidalgo y Costilla International Airport', (SELECT id FROM cities WHERE name = 'Guadalajara')),
    ('EZE', 'Ministro Pistarini International Airport', (SELECT id FROM cities WHERE name = 'Buenos Aires')),
    ('SCL', 'Arturo Merino Benítez International Airport', (SELECT id FROM cities WHERE name = 'Santiago')),
    ('JNB', 'O.R. Tambo International Airport', (SELECT id FROM cities WHERE name = 'Johannesburg')),
    ('LOS', 'Murtala Muhammed International Airport', (SELECT id FROM cities WHERE name = 'Lagos')),
    ('NBO', 'Jomo Kenyatta International Airport', (SELECT id FROM cities WHERE name = 'Nairobi')),
    ('PEK', 'Beijing Capital International Airport', (SELECT id FROM cities WHERE name = 'Beijing')),
    ('ICN', 'Incheon International Airport', (SELECT id FROM cities WHERE name = 'Seoul')),
    ('BOM', 'Chhatrapati Shivaji Maharaj International Airport', (SELECT id FROM cities WHERE name = 'Mumbai')),
    ('BKK', 'Suvarnabhumi Airport', (SELECT id FROM cities WHERE name = 'Bangkok')),
    ('AKL', 'Auckland Airport', (SELECT id FROM cities WHERE name = 'Auckland')),
    ('NAN', 'Nadi International Airport', (SELECT id FROM cities WHERE name = 'Suva')),
    ('DPS', 'Ngurah Rai International Airport', (SELECT id FROM cities WHERE name = 'Bali')),
    ('LED', 'Pulkovo Airport', (SELECT id FROM cities WHERE name = 'St. Petersburg')),
    ('ARN', 'Stockholm Arlanda Airport', (SELECT id FROM cities WHERE name = 'Stockholm')),
    ('AMS', 'Amsterdam Airport Schiphol', (SELECT id FROM cities WHERE name = 'Amsterdam')),
    ('LIS', 'Lisbon Airport', (SELECT id FROM cities WHERE name = 'Lisbon')),
    ('ATH', 'Athens International Airport', (SELECT id FROM cities WHERE name = 'Athens')),
    ('ZRH', 'Zurich Airport', (SELECT id FROM cities WHERE name = 'Zurich')),
    ('SJO', 'Juan Santamaría International Airport', (SELECT id FROM cities WHERE name = 'San Jose')),
    ('LIM', 'Jorge Chávez International Airport', (SELECT id FROM cities WHERE name = 'Lima')),
    ('CMN', 'Mohammed V International Airport', (SELECT id FROM cities WHERE name = 'Rabat')),
    ('ACC', 'Kotoka International Airport', (SELECT id FROM cities WHERE name = 'Accra')),
    ('RUH', 'King Khalid International Airport', (SELECT id FROM cities WHERE name = 'Riyadh')),
    ('HAN', 'Noi Bai International Airport', (SELECT id FROM cities WHERE name = 'Hanoi')),
    ('MNL', 'Ninoy Aquino International Airport', (SELECT id FROM cities WHERE name = 'Manila')),
    ('SIN', 'Singapore Changi Airport', (SELECT id FROM cities WHERE name = 'Singapore')),
    ('POM', 'Jacksons International Airport', (SELECT id FROM cities WHERE name = 'Port Moresby')),
    ('NOU', 'La Tontouta International Airport', (SELECT id FROM cities WHERE name = 'Noumea')),
    ('KBP', 'Boryspil International Airport', (SELECT id FROM cities WHERE name = 'Kiev')),
    ('WAW', 'Warsaw Chopin Airport', (SELECT id FROM cities WHERE name = 'Warsaw')),
    ('PRG', 'Václav Havel Airport Prague', (SELECT id FROM cities WHERE name = 'Prague')),
    ('MDE', 'José María Córdova International Airport', (SELECT id FROM cities WHERE name = 'Medellin')),
    ('CCS', 'Simón Bolívar International Airport', (SELECT id FROM cities WHERE name = 'Caracas')),
    ('TUN', 'Tunis–Carthage International Airport', (SELECT id FROM cities WHERE name = 'Tunis')),
    ('EBB', 'Entebbe International Airport', (SELECT id FROM cities WHERE name = 'Uganda')),
    ('IST', 'Istanbul Airport', (SELECT id FROM cities WHERE name = 'Istanbul')),
    ('KUL', 'Kuala Lumpur International Airport', (SELECT id FROM cities WHERE name = 'Kuala Lumpur')),
    ('DAC', 'Shahjalal International Airport', (SELECT id FROM cities WHERE name = 'Dhaka')),
    ('CMB', 'Bandaranaike International Airport', (SELECT id FROM cities WHERE name = 'Colombo')),
    ('HIR', 'Honiara International Airport', (SELECT id FROM cities WHERE name = 'Honiara')),
    ('APW', 'Faleolo International Airport', (SELECT id FROM cities WHERE name = 'Apia'));


-- Hotels
INSERT INTO hotels (name, city_id, standard, description)
VALUES ('Luxury Eiffel Hotel', 1, '*****', 'Exclusive hotel with a view of the Eiffel Tower.'),
       ('Roman Residence', 2, '****', 'Charming hotel with traditional Italian charm.'),
       ('Central New York Resort', 3, '*****', 'Luxury hotel in the heart of New York.'),
       ('Tropical Paradise in Rio', 4, '****', 'Comfortable hotel surrounded by beaches and jungle.'),
       ('Luxury Resort in Cairo', 5, '*****', 'Elegant hotel with a view of Cairos ancient sites.'),
       ('Japanese Zen in Tokyo', 6, '*****', 'Modern hotel in Japanese style.'),
       ('Coastal Haven in Sydney', 7, '****', 'Hotel with a view of Sydneys beautiful coastline.');

INSERT INTO hotels (name, city_id, standard, description)
VALUES
    ('Hotel Berlin', 1, '****', 'A luxurious hotel in the heart of Berlin.'),
    ('Madrid Grand Hotel', 2, '*****', 'Experience luxury at its finest in Madrid.'),
    ('Toronto Tower Hotel', 3, '****', 'Enjoy a comfortable stay with a view of Toronto.'),
    ('Guadalajara Resort', 4, '***', 'A peaceful resort in Guadalajara.'),
    ('Buenos Aires Boutique Hotel', 5, '****', 'Charming boutique hotel in Buenos Aires.'),
    ('Santiago View Inn', 6, '***', 'Panoramic views from this cozy inn in Santiago.'),
    ('Johannesburg Safari Lodge', 7, '*****', 'Experience the wild at our safari lodge.'),
    ('Lagos Beachfront Resort', 8, '****', 'Relax by the beach in Lagos.'),
    ('Nairobi Safari Camp', 9, '***', 'Explore the wilderness from our camp in Nairobi.'),
    ('Beijing Palace Hotel', 10, '*****', 'Luxury and opulence in the heart of Beijing.'),
    ('Seoul Skyline Hotel', 11, '****', 'Enjoy the Seoul skyline from your room.'),
    ('Mumbai Beach Resort', 12, '****', 'Relax by the beach in Mumbai.'),
    ('Bangkok City Hotel', 13, '***', 'Explore the vibrant city of Bangkok.'),
    ('Auckland Harborview Hotel', 14, '****', 'Scenic views of Auckland Harbor.'),
    ('Suva Tropical Retreat', 15, '***', 'Escape to a tropical paradise in Suva.'),
    ('Bali Beach Resort', 16, '*****', 'Experience luxury on the beaches of Bali.'),
    ('St. Petersburg Palace Hotel', 17, '****', 'A palace-like hotel in St. Petersburg.'),
    ('Stockholm City Center Hotel', 18, '****', 'Stay in the heart of Stockholm.'),
    ('Amsterdam Canal Hotel', 19, '****', 'Charming hotel along Amsterdams canals.'),
    ('Lisbon Historic Inn', 20, '***', 'Experience history in Lisbon.'),
    ('Athens Acropolis Hotel', 21, '****', 'View the Acropolis from your room in Athens.'),
    ('Zurich Lakeside Retreat', 22, '*****', 'Relax by the lakeside in Zurich.'),
    ('San Jose Downtown Hotel', 23, '***', 'Explore San Jose from our downtown hotel.'),
    ('Lima Coastal Resort', 24, '****', 'Enjoy the coast of Lima at our resort.'),
    ('Rabat Medina Hotel', 25, '****', 'Stay in the heart of Rabat Medina.'),
    ('Accra Beachfront Resort', 26, '*****', 'Beachfront luxury in Accra.'),
    ('Riyadh Business Hotel', 27, '****', 'Ideal for business travelers in Riyadh.'),
    ('Hanoi Old Quarter Hotel', 28, '***', 'Discover the charm of Hanoi Old Quarter.'),
    ('Manila Bayview Hotel', 29, '****', 'Enjoy a view of Manila Bay from your room.'),
    ('Singapore Marina Hotel', 30, '*****', 'Luxury by the marina in Singapore.'),
    ('Port Moresby Urban Hotel', 31, '***', 'Urban comfort in Port Moresby.'),
    ('Noumea Island Resort', 32, '****', 'Experience island paradise in Noumea.'),
    ('Kiev City Hotel', 33, '****', 'Stay in the heart of Kiev.'),
    ('Warsaw Royal Palace Hotel', 34, '*****', 'Experience royalty in Warsaw.'),
    ('Prague Old Town Hotel', 35, '****', 'Explore the charm of Prague Old Town.'),
    ('Medellin Mountain Retreat', 36, '***', 'Escape to the mountains in Medellin.'),
    ('Caracas City View Hotel', 37, '****', 'Enjoy city views in Caracas.'),
    ('Tunis Beach Resort', 38, '****', 'Relax by the beach in Tunis.'),
    ('Uganda Safari Lodge', 39, '*****', 'Safari adventure in Uganda.'),
    ('Istanbul Historic Hotel', 40, '****', 'Experience history in Istanbul.'),
    ('Kuala Lumpur City Hotel', 41, '****', 'Stay in the heart of Kuala Lumpur.'),
    ('Dhaka Business Hotel', 42, '***', 'Ideal for business travelers in Dhaka.'),
    ('Colombo Beachfront Resort', 43, '****', 'Beachfront luxury in Colombo.'),
    ('Honiara Island Retreat', 44, '***', 'Escape to an island retreat in Honiara.'),
    ('Apia Tropical Resort', 45, '****', 'Experience tropical paradise in Apia.');


-- Tours
INSERT INTO tours (departure_date, from_city, from_airport, to_city, to_airport, hotel, return_date, number_of_days,
                   type_of_board, price_for_adult, price_for_kid, is_promoted, number_of_adults, number_of_kids)
VALUES ('2023-09-10', 1, 'CDG', 2, 'FCO', 2, '2023-09-20', 10, 'All Inclusive', 2500.00, 1500.00, true, 2, 1),
       ('2023-08-15', 3, 'JFK', 4, 'GIG', 4, '2023-08-25', 10, 'Full Board', 1800.00, 1000.00, true, 2, 2),
       ('2023-09-25', 5, 'CAI', 6, 'HND', 6, '2023-10-05', 10, 'Bed and Dinner', 2200.00, 1200.00, true, 1, 2),
       ('2023-10-25', 5, 'CAI', 6, 'HND', 6, '2023-11-05', 10, 'Bed and Dinner', 2400.00, 1600.00, false, 1, 2),
       ('2023-10-10', 7, 'SYD', 1, 'CDG', 1, '2023-10-20', 10, 'All Inclusive', 2800.00, 1600.00, true, 2, 1);

-- Tour_orders
INSERT INTO tour_orders (order_date, tour)
VALUES ('2023-06-15', 1),
       ('2023-07-23', 2),
       ('2023-07-29', 3),
       ('2023-08-02', 4),
       ('2023-03-02', 5);